# Python Programming — Practical Manual

**SVKM's NMIMS — Nilkamal School of Mathematics, Applied Statistics & Analytics**
**B.Sc. (Applied Statistics & Analytics) — Semester I**

**Compiled by: Prof. Tirup Parmar**

---

### How to use this notebook in Google Colab
1. Open [colab.research.google.com](https://colab.research.google.com), then **File → Upload notebook** and select this `.ipynb` file (or open it directly from Google Drive/GitHub).
2. Run cells **in order**, top to bottom, using **Shift + Enter**. Within a session, later programs sometimes reuse an `import` from an earlier program in the *same* session.
3. Wherever a program uses `input(...)`, Colab will show a text box under the cell — type the value and press Enter.
4. **Session 14 (NumPy statistics)** uses a dataset file `student_scores.csv`. Before running that section, upload it using the cell provided at the start of Session 14 (or mount your Google Drive if you've stored it there).
5. Each session below contains: **Aim → Programs (with expected output as a comment) → Practice Exercises** for you to attempt on your own.

---


## Table of Contents

1. [Session 1: Beginning Python Basics: The print statement, Comments, Python Data Types](#session-1)
2. [Session 2: Python Data Structures and its functions: Lists, Tuple](#session-2)
3. [Session 3: Python Data Structures and its functions: Set, Dictionary](#session-3)
4. [Session 4: String Operations in Python, Simple Input & Output](#session-4)
5. [Session 5: Simple Output Formatting, Operators in Python](#session-5)
6. [Session 6: Python Program Flow, Indentation, The If Statement and Related Statements, The While Loop](#session-6)
7. [Session 7: The For Loop, The Range Statement, Examples for Looping](#session-7)
8. [Session 8: Break, Continue and Pass Statements, Examples for the Control Statements Along with the Loops](#session-8)
9. [Session 9: Functions & Modules - I: Create Your Own Functions, Parameters, Variable Arguments, Scope of a Function](#session-9)
10. [Session 10: Functions & Modules - 2: Call by Value, Call by Reference, Return Statement](#session-10)
11. [Session 11: Call by Value, Call by Reference, Return Statement (contd.); Searching Arrays and Sorting Arrays](#session-11)
12. [Session 12: Parallel Arrays, Multidimensional Arrays, Dynamic Arrays](#session-12)
13. [Session 13: NumPy Basics: Creating 1-D and 2-D Arrays, Displaying Array Members](#session-13)
14. [Session 14: NumPy Basics: Arrays and Functions, Math Statistics with Arrays, NumPy Arithmetic & Statistical Operations](#session-14)
15. [Session 15: NumPy Functions: arange, linspace, Random Number Generation, Seed, Reshape, Ravel](#session-15)

---
<a id="session-1"></a>
## Session 1: Beginning Python Basics: The print statement, Comments, Python Data Types

**Aim:** To understand and use Python's print statement, comments, and fundamental data types.


### Program 1: Different ways to use the print statement

In [1]:
print("Hello, World!")
print("Welcome", "to", "Python")
print("Welcome", "to", "Python", sep="-")
print("No newline here...", end=" ")
print("continues on the same line")

# Expected Output:
# Hello, World!
# Welcome to Python
# Welcome-to-Python
# No newline here... continues on the same line

Hello, World!
Welcome to Python
Welcome-to-Python
No newline here... continues on the same line


### Program 2: Using comments in Python

In [2]:
# This is a single-line comment
print("This line runs")   # inline comment explaining this line

"""
This is a multi-line comment (docstring),
often used to describe what a file or function does.
"""
print("Comments are ignored by Python")

# Expected Output:
# This line runs
# Comments are ignored by Python

This line runs
Comments are ignored by Python


### Program 3: Exploring Python's basic data types

In [3]:
a = 10            # int
b = 3.14          # float
c = "NMIMS"       # str
d = True          # bool
e = 2 + 3j        # complex
f = None          # NoneType

for value in (a, b, c, d, e, f):
    print(value, '->', type(value))

# Expected Output:
# 10 -> <class 'int'>
# 3.14 -> <class 'float'>
# NMIMS -> <class 'str'>
# True -> <class 'bool'>
# (2+3j) -> <class 'complex'>
# None -> <class 'NoneType'>

10 -> <class 'int'>
3.14 -> <class 'float'>
NMIMS -> <class 'str'>
True -> <class 'bool'>
(2+3j) -> <class 'complex'>
None -> <class 'NoneType'>


### Program 4: Simple arithmetic display using print

In [4]:
length = 12
breadth = 5
print("Area of rectangle =", length * breadth)
print("Perimeter of rectangle =", 2 * (length + breadth))

# Expected Output:
# Area of rectangle = 60
# Perimeter of rectangle = 34

Area of rectangle = 60
Perimeter of rectangle = 34


### Practice Exercises (attempt these yourself)

1. Write a program to print your name, college name, and course, each on a separate line.
2. Write a program that declares one variable of each data type (int, float, str, bool) and prints its type.

In [ ]:
# Write your exercise solutions here
# 1.
print("My name is John Doe.")
print("I am in NMIMS.")
print("I am studying AMC")

# 2.
w = True
x = 5
y = 10.5
z = "Hello"

print("The value of w is:", w)
print("The value of x is:", x)
print("The value of y is:", y)
print("The value of z is:", z)


---
<a id="session-2"></a>
## Session 2: Python Data Structures and its functions: Lists, Tuple

**Aim:** To create, access, and manipulate Lists and Tuples in Python.


### Program 1: List creation, indexing and slicing

In [6]:
fruits = ["apple", "banana", "cherry", "mango"]
print(fruits)
print(fruits[0])
print(fruits[-1])
print(fruits[1:3])

# Expected Output:
# ['apple', 'banana', 'cherry', 'mango']
# apple
# mango
# ['banana', 'cherry']

['apple', 'banana', 'cherry', 'mango']
apple
mango
['banana', 'cherry']


### Program 2: Common list methods

In [7]:
numbers = [5, 2, 9, 1]
numbers.append(20)
numbers.insert(1, 100)
numbers.sort()
print(numbers)
numbers.remove(100)
print(numbers)
print("Length:", len(numbers))

# Expected Output:
# [1, 2, 5, 9, 20, 100]
# [1, 2, 5, 9, 20]
# Length: 5

[1, 2, 5, 9, 20, 100]
[1, 2, 5, 9, 20]
Length: 5


### Program 3: Tuple creation and immutability

In [8]:
point = (10, 20)
print(point[0], point[1])

coordinates = (12.9, 77.6)
lat, lon = coordinates       # tuple unpacking
print(lat, lon)

# point[0] = 99   # Uncommenting this line raises TypeError -- tuples are immutable

# Expected Output:
# 10 20
# 12.9 77.6

10 20
12.9 77.6


### Program 4: List vs Tuple -- a quick comparison

In [9]:
my_list = [1, 2, 3]
my_tuple = (1, 2, 3)

my_list[0] = 99          # allowed
print("List after change:", my_list)
print("Tuple stays same:", my_tuple)

# Expected Output:
# List after change: [99, 2, 3]
# Tuple stays same: (1, 2, 3)

List after change: [99, 2, 3]
Tuple stays same: (1, 2, 3)


### Practice Exercises (attempt these yourself)

1. Write a program to find the largest and smallest number in a list without using max()/min().
2. Write a program that swaps the first and last elements of a list.
3. Create a tuple of 5 subjects and print them using a for loop.

In [ ]:
# Write your exercise solutions here
# 1.
elements = int(input("Enter the number of elements: "))
list_of_elements = []
for i in range(elements):
    num = int(input("Enter element {}: ".format(i + 1)))
    list_of_elements.append(num)
print("List of elements:", list_of_elements)
print("the greatest number is:", max(list_of_elements), "the smallest number is:", min(list_of_elements))
list_of_elements.sort()
print("the min and max is: ", list_of_elements[0], "and", list_of_elements[-1])

# 2.
list1 = [1, 2, 3]
list1[0], list1[-1] = list1[-1], list1[0]  # Swapping first and last elements
#a = list1[0]
#b = list1[-1]
#list1[0] = b
#list1[-1] = a
print("List after swapping first and last elements:", list1)

# 3.
tupple1 = ("math", "java", "python", "physics", "chemistry")
for i in tupple1:
    print(i, end="\n")
    

List after swapping first and last elements: [3, 2, 1]
math
java
python
physics
chemistry


---
<a id="session-3"></a>
## Session 3: Python Data Structures and its functions: Set, Dictionary

**Aim:** To create, access, and manipulate Sets and Dictionaries in Python.


### Program 1: Set creation and operations

In [12]:
A = {1, 2, 3, 4}
B = {3, 4, 5, 6}

print("Union:", A | B)
print("Intersection:", A & B)
print("Difference:", A - B)

A.add(10)
print("After add:", A)

# Expected Output:
# Union: {1, 2, 3, 4, 5, 6}
# Intersection: {3, 4}
# Difference: {1, 2}
# After add: {1, 2, 3, 4, 10}

Union: {1, 2, 3, 4, 5, 6}
Intersection: {3, 4}
Difference: {1, 2}
After add: {1, 2, 3, 4, 10}


### Program 2: Removing duplicates using a set

In [13]:
numbers = [4, 8, 4, 6, 8, 2, 6, 1]
unique_numbers = list(set(numbers))
print("Original:", numbers)
print("Unique:", sorted(unique_numbers))

# Expected Output:
# Original: [4, 8, 4, 6, 8, 2, 6, 1]
# Unique: [1, 2, 4, 6, 8]

Original: [4, 8, 4, 6, 8, 2, 6, 1]
Unique: [1, 2, 4, 6, 8]


### Program 3: Dictionary creation and access

In [14]:
student = {"name": "Rhea", "age": 20, "course": "BSc AS&A"}
print(student["name"])
student["age"] = 21
student["college"] = "NMIMS"
print(student)

for key, value in student.items():
    print(key, "->", value)

# Expected Output:
# Rhea
# {'name': 'Rhea', 'age': 21, 'course': 'BSc AS&A', 'college': 'NMIMS'}
# name -> Rhea
# age -> 21
# course -> BSc AS&A
# college -> NMIMS

Rhea
{'name': 'Rhea', 'age': 21, 'course': 'BSc AS&A', 'college': 'NMIMS'}
name -> Rhea
age -> 21
course -> BSc AS&A
college -> NMIMS


### Program 4: Word frequency counter using a dictionary

In [14]:
sentence = "the cat sat on the mat the cat ran"
words = sentence.split()
frequency = {}

for word in words:
    frequency[word] = frequency.get(word, 0) + 1

print(frequency)

# Expected Output:
# {'the': 3, 'cat': 2, 'sat': 1, 'on': 1, 'mat': 1, 'ran': 1}

{'the': 3, 'cat': 2, 'sat': 1, 'on': 1, 'mat': 1, 'ran': 1}


### Practice Exercises (attempt these yourself)

1. Write a program to check if two sets have any elements in common.
2. Write a program that stores 5 students and their marks in a dictionary and prints the topper.

In [10]:
# Write your exercise solutions here
# 1.
set1 = []
number_of_elements_set1 = int(input("Enter the number of elements in the first set: "))

for a in range(number_of_elements_set1):
    element = input("Enter an element for the first set: ")
    set1.append(element)

set2 = []
number_of_elements_set2 = int(input("Enter the number of elements in the second set: "))
for b in range(number_of_elements_set2):
    element = input("Enter an element for the second set: ")
    set2.append(element)

set1 = set(set1)
set2 = set(set2)

print("First set:", set1)
print("Second set:", set2)
print("Elements common to both sets:", set1 & set2)

# 2.
students_grades = {}
for i in range(5):
    name = input("Enter student name: ")
    grade = input("Enter student grade: ")
    students_grades[name] = grade

print("the student with the highest grade is:", max(students_grades, key=students_grades.get), "with grade:", students_grades[max(students_grades, key=students_grades.get)])

First set: {'1'}
Second set: {'1'}
Elements common to both sets: {'1'}
the student with the highest grade is: Cd11 with grade: 18


---
<a id="session-4"></a>
## Session 4: String Operations in Python, Simple Input & Output

**Aim:** To perform common string operations and use Python's input/output statements.


### Program 1: String indexing, slicing and basic operations

In [16]:
word = "PYTHON"
print(word[0], word[-1])
print(word[1:4])
print(word[::-1])
print(len(word))

# Expected Output:
# P N
# YTH
# NOHTYP
# 6

P N
YTH
NOHTYP
6


### Program 2: Common string methods

In [17]:
name = "  Tirup Parmar  "
print(name.strip())
print(name.strip().upper())
print(name.strip().lower())
print(name.strip().replace("Tirup", "Prof. Tirup"))
print(name.strip().split(" "))

# Expected Output:
# Tirup Parmar
# TIRUP PARMAR
# tirup parmar
# Prof. Tirup Parmar
# ['Tirup', 'Parmar']

Tirup Parmar
TIRUP PARMAR
tirup parmar
Prof. Tirup Parmar
['Tirup', 'Parmar']


### Program 3: Taking input from the user

In [6]:
name = input("Enter your name: ")
age = int(input("Enter your age: "))
print("Hello,", name, "- next year you will be", age + 1)

# Expected Output:
# Enter your name: Aarav
# Enter your age: 19
# Hello, Aarav - next year you will be 20

Hello, idare - next year you will be 4


### Program 4: Palindrome check (combining string + input/output)

In [ ]:
text = input("Enter a word: ").lower().replace(" ", "")
if text == text[::-1]:
    print("It IS a palindrome")
else:
    print("It is NOT a palindrome")

# Expected Output:
# Enter a word: madam
# It IS a palindrome

### Practice Exercises (attempt these yourself)

1. Write a program to count the number of vowels in a string entered by the user.
2. Write a program that accepts two strings and prints them concatenated with a space in between.

In [ ]:
# Write your exercise solutions here

# 1.
user_input = input("Enter a string: ")
number_of_vowels = 0

for char in user_input.lower():
    if char in 'aeiou':
        number_of_vowels += 1

print("Number of vowels in the string:", number_of_vowels)

# 2.
first_user_input = input("Enter the first string: ")
second_user_input = input("Enter the second string: ")

print("the concatenated string is:", first_user_input + " " + second_user_input)

Number of vowels in the string: 2
the concatenated string is: worldhelo


---
<a id="session-5"></a>
## Session 5: Simple Output Formatting, Operators in Python

**Aim:** To format program output cleanly and use Python's arithmetic, relational, and logical operators.


### Program 1: Output formatting using f-strings and format()

In [ ]:
name = "Tirup"
marks = 92.5678

print(f"Name: {name}, Marks: {marks:.2f}")
print("Name: {}, Marks: {:.2f}".format(name, marks))
print(f"{'Item':<10}{'Price':>10}")
print(f"{'Pen':<10}{10:>10}")

# Expected Output:
# Name: Tirup, Marks: 92.57
# Name: Tirup, Marks: 92.57
# Item           Price
# Pen               10

### Program 2: Arithmetic operators

In [ ]:
a, b = 17, 5
print("Sum:", a + b)
print("Difference:", a - b)
print("Product:", a * b)
print("Division:", a / b)
print("Floor Division:", a // b)
print("Modulus:", a % b)
print("Exponent:", a ** 2)

# Expected Output:
# Sum: 22
# Difference: 12
# Product: 85
# Division: 3.4
# Floor Division: 3
# Modulus: 2
# Exponent: 289

### Program 3: Relational and logical operators

In [ ]:
x, y = 10, 20
print(x == y, x != y, x < y)
print((x < y) and (y < 30))
print((x > y) or (y > 15))
print(not (x == y))

# Expected Output:
# False True True
# True
# True
# True

### Program 4: A neatly formatted multiplication table

In [ ]:
num = 7
for i in range(1, 11):
    print(f"{num} x {i:2} = {num*i:3}")

# Expected Output:
# 7 x  1 =   7
# 7 x  2 =  14
# ...
# 7 x 10 =  70

### Practice Exercises (attempt these yourself)

1. Write a program to display a bill with item name, quantity, price, and total, neatly formatted using f-strings.
2. Write a program to check whether a number is divisible by both 3 and 5 using logical operators.

In [ ]:
# Write your exercise solutions here


---
<a id="session-6"></a>
## Session 6: Python Program Flow, Indentation, The If Statement and Related Statements, The While Loop

**Aim:** To understand Python's indentation-based program flow, implement conditional statements, and use the while loop.


### Program 1: Simple if / elif / else -- grading system

In [ ]:
marks = int(input("Enter marks: "))

if marks >= 90:
    grade = "A"
elif marks >= 75:
    grade = "B"
elif marks >= 50:
    grade = "C"
else:
    grade = "F"

print("Grade:", grade)

# Expected Output:
# Enter marks: 82
# Grade: B

### Program 2: Nested if -- checking sign and parity together

In [ ]:
num = int(input("Enter a number: "))
if num >= 0:
    if num % 2 == 0:
        print("Positive and Even")
    else:
        print("Positive and Odd")
else:
    print("Negative number")

# Expected Output:
# Enter a number: 8
# Positive and Even

### Program 3: While loop -- sum of digits

In [ ]:
num = int(input("Enter a number: "))
original = num
total = 0
while num > 0:
    digit = num % 10
    total += digit
    num //= 10
print(f"Sum of digits of {original} = {total}")

# Expected Output:
# Enter a number: 4321
# Sum of digits of 4321 = 10

### Program 4: While loop -- number guessing game

In [ ]:
secret = 7
while True:
    guess = int(input("Guess the number (1-10): "))
    if guess == secret:
        print("Correct!")
        break
    elif guess < secret:
        print("Too low")
    else:
        print("Too high")

# Expected Output:
# Guess the number (1-10): 5
# Too low
# Guess the number (1-10): 7
# Correct!

### Practice Exercises (attempt these yourself)

1. Write a program to check if a year entered by the user is a leap year.
2. Write a program using a while loop to display the multiplication table of a number.

In [ ]:
# Write your exercise solutions here


---
<a id="session-7"></a>
## Session 7: The For Loop, The Range Statement, Examples for Looping

**Aim:** To use the for loop and range() function to iterate over sequences and numeric ranges.


### Program 1: for loop with range()

In [ ]:
for i in range(1, 6):
    print(i, "->", i ** 2)

# Expected Output:
# 1 -> 1
# 2 -> 4
# 3 -> 9
# 4 -> 16
# 5 -> 25

### Program 2: range() with a step value

In [ ]:
for i in range(0, 20, 5):
    print(i, end=" ")
print()
for i in range(10, 0, -2):
    print(i, end=" ")

# Expected Output:
# 0 5 10 15
# 10 8 6 4 2

### Program 3: for loop over a list and a string

In [ ]:
fruits = ["apple", "banana", "cherry"]
for fruit in fruits:
    print(fruit.upper())

for ch in "Hi!":
    print(ch)

# Expected Output:
# APPLE
# BANANA
# CHERRY
# H
# i
# !

### Program 4: Nested for loop -- pattern printing

In [2]:
rows = 5
for i in range(1, rows + 1):
    for j in range(i):
        print("*", end="")
    print()

# Expected Output:
# *
# **
# ***
# ****
# *****

*
**
***
****
*****


### Practice Exercises (attempt these yourself)

1. Write a program to print all even numbers between 1 and 50 using range().
2. Write a program to print a multiplication table (1 to 10) for a number using a for loop.
3. Write a program to print a number pyramid: 1 / 1 2 / 1 2 3 / 1 2 3 4.

In [ ]:
# Write your exercise solutions here


---
<a id="session-8"></a>
## Session 8: Break, Continue and Pass Statements, Examples for the Control Statements Along with the Loops

**Aim:** To control loop execution using break, continue, and pass statements.


### Program 1: break -- stop a loop early

In [3]:
numbers = [4, 8, 15, 16, 23, 42]
target = 16
for n in numbers:
    if n == target:
        print("Found", target)
        break
    print("Checked", n)

# Expected Output:
# Checked 4
# Checked 8
# Checked 15
# Found 16

Checked 4
Checked 8
Checked 15
Found 16


### Program 2: continue -- skip an iteration

In [ ]:
for i in range(1, 11):
    if i % 2 == 0:
        continue        # skip even numbers
    print(i, end=" ")

# Expected Output:
# 1 3 5 7 9

### Program 3: pass -- placeholder statement

In [ ]:
for i in range(1, 6):
    if i == 3:
        pass            # nothing happens, placeholder for future code
    print(i)

# Expected Output:
# 1
# 2
# 3
# 4
# 5

### Program 4: Combined example -- password attempt tracker

In [ ]:
correct_password = "python123"
for attempt in range(1, 4):
    entered = input(f"Attempt {attempt}: Enter password: ")
    if entered == correct_password:
        print("Access granted!")
        break
else:
    print("Access denied -- too many attempts")

# Expected Output:
# Attempt 1: Enter password: wrong
# Attempt 2: Enter password: python123
# Access granted!

### Practice Exercises (attempt these yourself)

1. Write a program that prints numbers from 1 to 50 but stops as soon as it finds a number divisible by both 7 and 5.
2. Write a program that prints all numbers from 1 to 30, skipping multiples of 3, using continue.

In [ ]:
# Write your exercise solutions here


---
<a id="session-9"></a>
## Session 9: Functions & Modules - I: Create Your Own Functions, Parameters, Variable Arguments, Scope of a Function

**Aim:** To define and call functions, work with parameters (including variable-length arguments), and understand variable scope.


### Program 1: Defining and calling a simple function

In [ ]:
def calculate_area(length, breadth):
    return length * breadth

print(calculate_area(5, 3))
print(calculate_area(10, 2))

# Expected Output:
# 15
# 20

### Program 2: Default parameters and keyword arguments

In [ ]:
def greet(name, greeting="Hello"):
    print(greeting, name)

greet("Rhea")
greet("Kabir", "Welcome")
greet(greeting="Hi", name="Zoya")

# Expected Output:
# Hello Rhea
# Welcome Kabir
# Hi Zoya

### Program 3: Variable-length arguments using *args

In [ ]:
def add_all(*numbers):
    return sum(numbers)

print(add_all(1, 2, 3))
print(add_all(10, 20, 30, 40))

# Expected Output:
# 6
# 100

### Program 4: Scope of a function -- local vs global

In [ ]:
x = 10                     # global variable

def show_value():
    y = 5                  # local variable
    print("Inside function:", x, y)

show_value()
print("Outside function:", x)
# print(y)   # This would raise NameError -- y only exists inside the function

# Expected Output:
# Inside function: 10 5
# Outside function: 10

### Practice Exercises (attempt these yourself)

1. Write a function is_prime(n) that returns True or False.
2. Write a function that accepts any number of arguments and returns their average using *args.

In [ ]:
# Write your exercise solutions here


---
<a id="session-10"></a>
## Session 10: Functions & Modules - 2: Call by Value, Call by Reference, Return Statement

**Aim:** To understand how arguments are passed to functions in Python, and how the return statement sends results back.


### Program 1: Call by Value behaviour (immutable arguments)

In [ ]:
def try_to_change(n):
    n = n + 100
    return n

x = 5
result = try_to_change(x)
print("Original x:", x)
print("Returned result:", result)

# Expected Output:
# Original x: 5
# Returned result: 105

### Program 2: Call by Reference behaviour (mutable arguments)

In [ ]:
def add_item(my_list):
    my_list.append("new item")

items = ["pen", "book"]
add_item(items)
print(items)      # original list WAS modified

# Expected Output:
# ['pen', 'book', 'new item']

### Program 3: Returning multiple values

In [ ]:
def get_min_max(numbers):
    return min(numbers), max(numbers)

lowest, highest = get_min_max([4, 8, 1, 9, 3])
print("Lowest:", lowest, "Highest:", highest)

# Expected Output:
# Lowest: 1 Highest: 9

### Program 4: A recursive function using return (factorial)

In [ ]:
def factorial(n):
    if n == 0 or n == 1:
        return 1
    return n * factorial(n - 1)

print(factorial(5))

# Expected Output:
# 120

### Practice Exercises (attempt these yourself)

1. Write a function that takes a list of prices and applies a 10% discount to each price IN PLACE (modifying the original list).
2. Write a recursive function to compute the sum of the first n natural numbers.

In [ ]:
# Write your exercise solutions here


---
<a id="session-11"></a>
## Session 11: Call by Value, Call by Reference, Return Statement (contd.); Searching Arrays and Sorting Arrays

**Aim:** To implement Linear Search, Binary Search, and Bubble Sort on arrays (lists).


### Program 1: Linear Search

In [ ]:
def linear_search(arr, target):
    for index, value in enumerate(arr):
        if value == target:
            return index
    return -1

scores = [42, 17, 8, 99, 23]
print(linear_search(scores, 99))
print(linear_search(scores, 100))

# Expected Output:
# 3
# -1

### Program 2: Binary Search (array must be sorted)

In [ ]:
def binary_search(arr, target):
    low, high = 0, len(arr) - 1
    while low <= high:
        mid = (low + high) // 2
        if arr[mid] == target:
            return mid
        elif arr[mid] < target:
            low = mid + 1
        else:
            high = mid - 1
    return -1

sorted_ids = [8, 17, 23, 42, 99]
print(binary_search(sorted_ids, 42))

# Expected Output:
# 3

### Program 3: Bubble Sort

In [ ]:
def bubble_sort(arr):
    n = len(arr)
    for i in range(n - 1):
        for j in range(n - 1 - i):
            if arr[j] > arr[j + 1]:
                arr[j], arr[j + 1] = arr[j + 1], arr[j]
    return arr

print(bubble_sort([5, 2, 9, 1, 7]))

# Expected Output:
# [1, 2, 5, 7, 9]

### Program 4: Using Python's built-in search/sort shortcuts

In [ ]:
numbers = [5, 2, 9, 1, 7]
print(99 in numbers)          # membership test
numbers.sort()
print(numbers)
print(sorted(numbers, reverse=True))

# Expected Output:
# False
# [1, 2, 5, 7, 9]
# [9, 7, 5, 2, 1]

### Practice Exercises (attempt these yourself)

1. Write a program to implement Selection Sort.
2. Write a program that searches for a student's name in a list and prints their position, or 'Not found'.

In [ ]:
# Write your exercise solutions here


---
<a id="session-12"></a>
## Session 12: Parallel Arrays, Multidimensional Arrays, Dynamic Arrays

**Aim:** To work with parallel arrays, multidimensional (2-D) arrays, and Python's dynamic array behaviour.


### Program 1: Parallel arrays

In [ ]:
names = ["Amit", "Bina", "Chirag"]
scores = [88, 72, 95]

for i in range(len(names)):
    print(f"{names[i]} scored {scores[i]}")

best_index = scores.index(max(scores))
print("Top scorer:", names[best_index])

# Expected Output:
# Amit scored 88
# Bina scored 72
# Chirag scored 95
# Top scorer: Chirag

### Program 2: Multidimensional (2-D) array using nested lists

In [ ]:
grid = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
]
print(grid[1][2])          # row 1, column 2

for row in grid:
    for value in row:
        print(value, end=" ")
    print()

# Expected Output:
# 6
# 1 2 3
# 4 5 6
# 7 8 9

### Program 3: Row and column sums of a 2-D array

In [ ]:
grid = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
for i, row in enumerate(grid):
    print(f"Row {i} sum: {sum(row)}")
for c in range(3):
    col_sum = sum(row[c] for row in grid)
    print(f"Column {c} sum: {col_sum}")

# Expected Output:
# Row 0 sum: 6
# Row 1 sum: 15
# Row 2 sum: 24
# Column 0 sum: 12
# Column 1 sum: 15
# Column 2 sum: 18

### Program 4: Dynamic array behaviour (Python lists grow automatically)

In [ ]:
data = []
for i in range(5):
    data.append(i * i)
    print(data)

# Expected Output:
# [0]
# [0, 1]
# [0, 1, 4]
# [0, 1, 4, 9]
# [0, 1, 4, 9, 16]

### Practice Exercises (attempt these yourself)

1. Write a program to find the transpose of a 3x3 matrix using nested lists.
2. Write a program using parallel arrays to store product names and prices, then print the cheapest product.

In [ ]:
# Write your exercise solutions here


---
<a id="session-13"></a>
## Session 13: NumPy Basics: Creating 1-D and 2-D Arrays, Displaying Array Members

**Aim:** To install/import NumPy and create and display one-dimensional and two-dimensional arrays.


### Program 1: Importing NumPy and creating a 1-D array

In [ ]:
import numpy as np

arr1 = np.array([10, 20, 30, 40, 50])
print(arr1)
print(type(arr1))
print("Shape:", arr1.shape)

# Expected Output:
# [10 20 30 40 50]
# <class 'numpy.ndarray'>
# Shape: (5,)

### Program 2: Creating a 2-D array

In [ ]:
import numpy as np

arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2)
print("Shape:", arr2.shape)
print("Dimensions:", arr2.ndim)
print("Total elements:", arr2.size)

# Expected Output:
# [[1 2 3]
#  [4 5 6]]
# Shape: (2, 3)
# Dimensions: 2
# Total elements: 6

### Program 3: Displaying array members (indexing, slicing, iteration)

In [ ]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])
print(arr[0], arr[-1])
print(arr[1:4])

for value in arr:
    print(value, end=" ")

# Expected Output:
# 10 50
# [20 30 40]
# 10 20 30 40 50

### Program 4: 2-D indexing and slicing

In [ ]:
import numpy as np

matrix = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print(matrix[1, 2])       # single element
print(matrix[0, :])       # entire first row
print(matrix[:, 1])       # entire second column

# Expected Output:
# 60
# [10 20 30]
# [20 50 80]

### Practice Exercises (attempt these yourself)

1. Write a program to create a 4x4 NumPy array of your choice and print its shape, size, and dimensions.
2. Write a program to extract the diagonal elements of a 3x3 NumPy array (without using np.diag).

In [ ]:
# Write your exercise solutions here


---
<a id="session-14"></a>
## Session 14: NumPy Basics: Arrays and Functions, Math Statistics with Arrays, NumPy Arithmetic & Statistical Operations

**Aim:** To perform arithmetic and statistical operations on NumPy arrays, including using a real dataset.


### Using the Dataset in Colab

Run the cell below once to upload `student_scores.csv` from your computer into this Colab session (the file is provided alongside this notebook).

In [ ]:
# Run this cell, then click "Choose Files" and select student_scores.csv
from google.colab import files
uploaded = files.upload()

### Program 1: Element-wise arithmetic operations

In [ ]:
import numpy as np
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])

print(a + b)
print(a * b)
print(b / a)

# Expected Output:
# [11 22 33]
# [10 40 90]
# [10. 10. 10.]

### Program 2: Basic statistics with NumPy

In [ ]:
import numpy as np

scores = np.array([88, 72, 95, 60, 45, 78, 91])
print("Sum:", np.sum(scores))
print("Mean:", np.mean(scores))
print("Median:", np.median(scores))
print("Variance:", np.var(scores))
print("Std Dev:", round(np.std(scores), 2))

# Expected Output:
# Sum: 529
# Mean: 75.57142857142857
# Median: 78.0
# Variance: 280.81632653061223
# Std Dev: 16.76

### Program 3: Loading the student_scores.csv dataset and computing statistics

*Note: Upload student_scores.csv to your Colab session first (see the 'Using the Dataset in Colab' note at the top of this notebook).*

In [ ]:
import numpy as np

# Load only the numeric columns (Maths, Statistics, Python, Economics), skipping the header and name column
data = np.genfromtxt("student_scores.csv", delimiter=",", skip_header=1, usecols=(1, 2, 3, 4))
print(data)

subjects = ["Maths", "Statistics", "Python", "Economics"]
subject_means = np.mean(data, axis=0)     # mean of each COLUMN (subject)
for subject, mean in zip(subjects, subject_means):
    print(f"{subject} average: {mean:.2f}")

student_totals = np.sum(data, axis=1)     # sum of each ROW (student)
print("Highest total score:", np.max(student_totals))

# Expected Output:
# [[88. 92. 79. 85.]
#  [45. 60. 55. 50.]
#  ... (10 rows total)
#  [63. 70. 66. 68.]]
# Maths average: 69.40
# Statistics average: 71.00
# Python average: 70.90
# Economics average: 69.50
# Highest total score: 377.0

### Program 4: A reusable function combining Functions (Session 9-10) with NumPy

In [ ]:
import numpy as np

def summarize(data):
    arr = np.array(data)
    return arr.mean(), arr.var(), arr.std()

mean, var, std = summarize([10, 20, 30, 40, 50])
print(f"Mean={mean}, Variance={var}, Std={std:.2f}")

# Expected Output:
# Mean=30.0, Variance=200.0, Std=14.14

### Practice Exercises (attempt these yourself)

1. Using student_scores.csv, write a program to find which student scored the highest total across all subjects.
2. Write a program to compute the standard deviation of each subject in the dataset.

In [ ]:
# Write your exercise solutions here


---
<a id="session-15"></a>
## Session 15: NumPy Functions: arange, linspace, Random Number Generation, Seed, Reshape, Ravel

**Aim:** To use NumPy's array-generation functions and understand reshaping and flattening of arrays.


### Program 1: arange() and linspace()

In [ ]:
import numpy as np

a = np.arange(0, 20, 4)          # start, stop, STEP
print("arange:", a)

b = np.linspace(0, 1, 5)         # start, stop, NUMBER OF POINTS
print("linspace:", b)

# Expected Output:
# arange: [ 0  4  8 12 16]
# linspace: [0.   0.25 0.5  0.75 1.  ]

### Program 2: Random number generation and seeding

In [ ]:
import numpy as np

np.random.seed(42)              # fixes the randomness so results are REPRODUCIBLE
random_arr = np.random.rand(5)  # 5 random floats between 0 and 1
print(random_arr)

dice_rolls = np.random.randint(1, 7, size=10)   # 10 random integers from 1 to 6
print(dice_rolls)

# Expected Output:
# [0.37454012 0.95071431 0.73199394 0.59865848 0.15601864]
# [3 3 3 5 4 3 6 5 2 4]   (exact values may vary slightly by NumPy version, but will REPEAT every run because of the seed)

### Program 3: Reshape

In [ ]:
import numpy as np

arr = np.arange(1, 13)          # 12 elements
print(arr)

reshaped = arr.reshape(3, 4)    # 3 rows x 4 columns = 12
print(reshaped)

# Expected Output:
# [ 1  2  3  4  5  6  7  8  9 10 11 12]
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]

### Program 4: Ravel -- flattening a multidimensional array

In [ ]:
import numpy as np

matrix = np.array([[1, 2, 3], [4, 5, 6]])
flat = matrix.ravel()
print("Original:", matrix.tolist())
print("Flattened:", flat)

# Expected Output:
# Original: [[1, 2, 3], [4, 5, 6]]
# Flattened: [1 2 3 4 5 6]

### Practice Exercises (attempt these yourself)

1. Write a program to generate 20 evenly spaced values between 0 and 100 using linspace().
2. Write a program to create a 5x5 array using arange() and reshape(), then flatten it back using ravel().
3. Write a program that uses np.random.seed(10) and prints 5 random integers between 50 and 100.

In [ ]:
# Write your exercise solutions here


---
## End of Practical Manual

**Prof. Tirup Parmar**
SVKM's NMIMS — Nilkamal School of Mathematics, Applied Statistics & Analytics
